SchemaVersion: '1.0'
SageMaker:
  PythonSDK:
    Modules:
      RemoteFunction:
        Dependencies: ./requirements.txt
        # Using Python 3.10 for SageMaker JupyterLab compatibility
        #Ensure container Python version matches your notebook environment
        ImageUri: '763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training:2.2.0-gpu-py310'  
        InstanceType: ml.g5.12xlarge
        IncludeLocalWorkDir: true
        PreExecutionCommands:
          - 'export NCCL_P2P_DISABLE=1'
        CustomFileFilter:
          IgnoreNamePatterns:
          - "data/*"
          - "models/*"
          - "*.ipynb"
          - "*.csv"
          - "*.md"
          - "__pycache__"
          - ".git/"
          - ".git/*"
          - ".git/**"
          - ".github/"
          - ".venv/"
        #RoleArn: RoleArn required if you are running the notebooks from a local IDE
        RoleArn: 'arn:aws:iam::974155583980:role/service-role/AmazonSageMaker-ExecutionRole-20240518T161187'
  Model:
    EnableNetworkIsolation: false